import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getEncoding } from "js-tiktoken";

const root = resolve(process.cwd());
const data = JSON.parse(
  readFileSync(resolve(root, "benchmarks/statement_savings_cases.json"), "utf8"),
);

function count(text, encodingName) {
  const encoder = getEncoding(encodingName);
  return encoder.encode(text).length;
}

function renderTable(rows) {
  const lines = [
    "| case | category | python tokens | dsl tokens | saved | reduction |",
    "| --- | --- | ---: | ---: | ---: | ---: |",
  ];
  for (const row of rows) {
    lines.push(
      `| ${row.name} | ${row.category} | ${row.pythonTokens} | ${row.dslTokens} | ${row.saved} | ${row.reduction}% |`,
    );
  }
  return lines.join("\n");
}

function renderDetails(rows) {
  return rows
    .map(
      (row) => [
        `### ${row.name}`,
        "",
        `- category: ${row.category}`,
        `- note: ${row.note}`,
        `- python: \`${row.python}\``,
        `- dsl: \`${row.dsl}\``,
        `- saved: ${row.saved} tokens (${row.reduction}%)`,
      ].join("\n"),
    )
    .join("\n\n");
}

const sections = [
  "# Statement-Level Token Savings",
  "",
  "This file is generated by `node scripts/report_statement_savings.mjs`.",
  "",
];

for (const encodingName of data.encodings) {
  const rows = data.cases.map((item) => {
    const pythonTokens = count(item.python, encodingName);
    const dslTokens = count(item.dsl, encodingName);
    const saved = pythonTokens - dslTokens;
    const reduction = pythonTokens === 0
      ? "0.00"
      : ((saved / pythonTokens) * 100).toFixed(2);
    return {
      ...item,
      pythonTokens,
      dslTokens,
      saved,
      reduction,
    };
  });

  console.log(`== ${encodingName} ==`);
  for (const row of rows) {
    console.log(
      `${row.name}: python=${row.pythonTokens}, dsl=${row.dslTokens}, saved=${row.saved}, reduction=${row.reduction}%`,
    );
  }
  console.log("");

  sections.push(`## ${encodingName}`);
  sections.push("");
  sections.push(renderTable(rows));
  sections.push("");
  sections.push(renderDetails(rows));
  sections.push("");
}

writeFileSync(
  resolve(root, "docs/statement_token_savings.md"),
  sections.join("\n"),
  "utf8",
);
